name: mini
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Prompts/Dating/prompt_set_x.json
    - assets/love_quotes.json
    - assets/Polaroid1.png
    - assets/Polaroid2.png
    - assets/Polaroid3.png
    - assets/Polaroid4.png
    - assets/chat_gpt_texture.png
    - assets/chat_gpt_texture_alt.png
