name: mini
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - Prompts/Dating/prompt_set_x.json
